### ISSUE TITLE
pre_training and fine-tune

### ISSUE THREAD

**Issue by Joker-ZXR** [microsoft/StyleSwin#13]
Hi, thank you so much for sharing your code！
I have a question. I'd like to transfer the model to medical images. 
But I don't I retrain directly or I need load the pre-training model and fine-tune it?
What do you think about it? Looking forward to your reply!

**Comment by ForeverFancy** [comment]
Thanks for your interest of our work. In my opinion, there might be a large gap between the distribution of medical images and our pretrained datasets. As a result, I think it might be more appropriate to retrain our model using your dataset. However, you could also try to fine-tune the model to see if it is feasible.

**Comment by Joker-ZXR** [comment]
Ok, thank you for your answer. I'll try it.
