### ISSUE TITLE
Source of FFHQ-256

### ISSUE THREAD

**Issue by hubert0527** [microsoft/StyleSwin#14]
Which source did you get the FFHQ-256 dataset from? The downsampling method can be a critical factor in FID evaluation. Thanks!

**Comment by ForeverFancy** [comment]
Hi, it is true that the downsampling method is important in FID evaluation.  We use the official FFHQ-1024 images and downsample them with PIL.Image.LANCZOS to get anti-aliasing scaled images.

**Comment by hubert0527** [comment]
Thanks!
