### ISSUE TITLE
About FLOPs

### ISSUE THREAD

**Issue by zhouwy19** [microsoft/StyleSwin#15]
When I print the flops of generator, there is an error. I found the 'self.attn' on line 356 is a list. In fact there are 2 attns to be calculated. How can I fix it? When I change 'self.attn' to 'self.attn[0]', the flops shows 68109933824.0 (68B), larger than 50.9B than paper.

![image](https://user-images.githubusercontent.com/43036573/162867450-bde7115a-3a3e-4c0c-94e0-aa8351c2fb0e.png)

**Comment by ForeverFancy** [comment]
Hi, thanks for pointing out this bug. We report the FLOPS of 1024 resolution with channel multiplier of generator set to 1, which is 46.44B after fixing the bug. And I will also update the paper in arxiv with the correct FLOPS.
