### ISSUE TITLE
Training log of losses

### ISSUE THREAD

**Issue by hanq0212** [microsoft/StyleSwin#16]
Hi,
Thank you for your awesome research!
I am training the model with my own dataset, i want to know the training logs of losses if it is possible.
Discriminator loss seems to converge so fast (close to 0) , is it right? 

Best regards,
Hankyu Jang

**Comment by ForeverFancy** [comment]
Hi, thanks for your interest of our work. The loss of D would not converge to 0 under normal conditions. Which loss logs do you want to know, I could send them to your mail.

**Comment by hanq0212** [comment]
Thank you for your answer. 
Can I know the graphs of G, D losses  in the tensorboard?

**Comment by ForeverFancy** [comment]
Hi, part of the training logs of FFHQ-256 could be viewed here.
[Loss of G](https://wandb.ai/foreverfancy/FFHQ256_BCR_ChannelM2_DoubleAttn_Alpha/reports/Shared-panel-22-04-21-11-04-17--VmlldzoxODcyMDQ1?accessToken=x3mum0t58x4xbcrfn01olt21w6cvr6oia75o3al256ii7void6d7wwvg9k4fdeuq), [loss of D](https://wandb.ai/foreverfancy/FFHQ256_BCR_ChannelM2_DoubleAttn_Alpha/reports/Shared-panel-22-04-21-11-04-55--VmlldzoxODcyMDUw?accessToken=59tpo71tm2ih271ti71acocoqp7z0azh2qymd4vb6sp444592d0246t328i6ftd6) and [r1_val](https://wandb.ai/foreverfancy/FFHQ256_BCR_ChannelM2_DoubleAttn_Alpha/reports/Shared-panel-22-04-21-11-04-07--VmlldzoxODcyMDUy?accessToken=7d0xtxxhc3qm6u3xbrnln3li3j6nuhjkloi8mft3alh38iy93tsm3kuciqvrg3ih).

**Comment by hanq0212** [comment]
Thank you!
