### ISSUE TITLE
Missing attribution for `Inceptionv3`

### ISSUE THREAD

**Issue by goodbadwolf** [microsoft/StyleSwin#18]
https://github.com/microsoft/StyleSwin/blob/main/utils/inception.py seems to be an exact copy, without any attribution, of https://github.com/mseitzer/pytorch-fid/blob/master/src/pytorch_fid/inception.py
with the exception of adding a copyright text @ Microsoft

**Comment by ForeverFancy** [comment]
Thanks for pointing out this. I will fix it.
