### ISSUE TITLE
显存问题

### ISSUE THREAD

**Issue by zhou431496** [microsoft/StyleSwin#19]
请问12g的显存可以运行改代码嘛，如果我将该模型作为一个生成器像stylegan一样。是否可以通过该预训练的模型进行人脸编辑？期待您的回复。

**Comment by ForeverFancy** [comment]
您好，通过减少 `batch size`，设置 `G_channel_multiplier, D_channel_multiplier = 1` 或者使用 `--use_checkpoint` 选项， 应该可以在 12G 显存上运行。StyleSwin 和 StyleGAN 一样是一个 general image generation model，参考修改 stylegan 的方法也可以将我们的模型修改为适合于人脸编辑的网络。谢谢。
