### ISSUE TITLE
Betas

### ISSUE THREAD

**Issue by TheGullahanMaster** [microsoft/StyleSwin#21]
Hello, i forgot to ask in the previous issue, but what is the intuition behind beta1=0.0 and beta2=0.99? I've seen it in a couple more projects (Such as CIPS), and i always wondered how did they come up with these values (As usually, GANs have beta1=0.5 and beta2=0.999). Is there some property of these values that helps training? Or is it just betas that seemed to work the most?

**Comment by TheGullahanMaster** [comment]
Also, did you experiment with an increase in the "depths" in models/generator.py? The default is 2 all the way, but when designing styleswin, did you try depth of 4, 12 etc...? What were the results?

**Comment by ForeverFancy** [comment]
> Hello, i forgot to ask in the previous issue, but what is the intuition behind beta1=0.0 and beta2=0.99? I've seen it in a couple more projects (Such as CIPS), and i always wondered how did they come up with these values (As usually, GANs have beta1=0.5 and beta2=0.999). Is there some property of these values that helps training? Or is it just betas that seemed to work the most?

We just follow this setting in StyleGAN2, which also provides the best performance among all settings.

**Comment by ForeverFancy** [comment]
> Also, did you experiment with an increase in the "depths" in models/generator.py? The default is 2 all the way, but when designing styleswin, did you try depth of 4, 12 etc...? What were the results?

To fairly compare with StyleGAN2, which uses 2 Conv layers in each resolution, we just set the depth to 2. Increasing the depth expects to improve the performance, but we didn't perform more experiments.

**Comment by TheGullahanMaster** [comment]
> > Also, did you experiment with an increase in the "depths" in models/generator.py? The default is 2 all the way, but when designing styleswin, did you try depth of 4, 12 etc...? What were the results?
> 
> To fairly compare with StyleGAN2, which uses 2 Conv layers in each resolution, we just set the depth to 2. Increasing the depth expects to improve the performance, but we didn't perform more experiments.

I'm currently trying out depth 12, with this coinfig
`        depths = [12, 12, 12, 12, 12, 12, 12, 12, 12]
        in_channels = [
            512, #4
            256, #8
            128, #16
            128, #32
            128 * channel_multiplier, #64
            64 * channel_multiplier, #128
            32 * channel_multiplier, #256
            16 * channel_multiplier, #512
            8 * channel_multiplier#1024
        ]  `
(my GPU cannot handle it at default values) on a tiny dataset of buildings(128x128), about 200, and it does seem somewhat faster, though it's not finished yet.
![eval_0_000002](https://user-images.githubusercontent.com/45826691/166853742-0202f7d9-dea4-43da-9df7-6d85e1e91dab.png)
![eval_0_000003](https://user-images.githubusercontent.com/45826691/166853743-0fc255d9-7a30-45bf-b289-6d5b9ee91481.png)
![eval_0_000004](https://user-images.githubusercontent.com/45826691/166853744-82420588-756d-4986-9f56-856e85432589.png)
![eval_0_000005](https://user-images.githubusercontent.com/45826691/166853745-252716ad-0531-4465-a67b-b454c288d414.png)
![eval_0_000006](https://user-images.githubusercontent.com/45826691/166853746-a51b80b0-fe21-404c-83b9-41f97215826b.png)
![eval_0_000007](https://user-images.githubusercontent.com/45826691/166853747-b84a0120-f472-4cde-becd-169dbd3942a8.png)
![eval_0_000008](https://user-images.githubusercontent.com/45826691/166853750-e83622ff-0bb3-4e37-b575-51cdcf112134.png)
![eval_0_000009](https://user-images.githubusercontent.com/45826691/166853752-5d7d6683-dd72-4a55-904f-1505fcf4a5f8.png)
![eval_0_000010](https://user-images.githubusercontent.com/45826691/166853755-9c4e28cd-1383-4adc-9016-3718202f8228.png)
![eval_0_000011](https://user-images.githubusercontent.com/45826691/166853756-66150576-35e3-45c6-9619-e3928110d008.png)
![eval_0_000012](https://user-images.githubusercontent.com/45826691/166853757-9ef46ee5-6763-4958-8d29-72a1f72bde52.png)
![eval_0_000013](https://user-images.githubusercontent.com/45826691/166853758-e4844941-92ad-464a-9212-1a8b780bf363.png)
![eval_0_000014](https://user-images.githubusercontent.com/45826691/166853761-e1f1c9bc-cba7-4a71-852f-aab8ac6e522f.png)
![eval_0_000015](https://user-images.githubusercontent.com/45826691/166853762-7b4a0d3c-9573-4efc-8161-b9ef2e93ba91.png)
![eval_0_000016](https://user-images.githubusercontent.com/45826691/166853763-fd8bcb5e-d604-4a02-9d95-ac150e554a6e.png)
![eval_0_000017](https://user-images.githubusercontent.com/45826691/166853764-bb081942-6bed-483e-8554-84a4c598fa3a.png)
![eval_0_000018](https://user-images.githubusercontent.com/45826691/166853766-68c6de6f-5d18-4567-874b-9c51148d6ed3.png)

**Comment by TheGullahanMaster** [comment]
The discriminator channels were modified as well, to match the generator's channels

**Comment by TheGullahanMaster** [comment]
One more question; What does `--enable_full_resolution` do? Default is 8, and it seem to set window size to 8 after it's ran through `int(math.log(enable_full_resolution, 2))`.

**Comment by ForeverFancy** [comment]
> One more question; What does `--enable_full_resolution` do? Default is 8, and it seem to set window size to 8 after it's ran through `int(math.log(enable_full_resolution, 2))`. Should i edit `--enable_full_resolution` to be smaller when doing smaller resolutions than 1024? Or should i leave it be?

This augment is used to set using `full resolution attention` (window size = resolution) util which resolution. Just set as default would be better.

**Comment by TheGullahanMaster** [comment]
Ok, thanks for clearing that up. Should i also use the default amount of channels per resolutions when doing smaller resolutions?

**Comment by ForeverFancy** [comment]
That's depend on the performance.

**Comment by TheGullahanMaster** [comment]
By performance, you mean how well the model is performing, or if it can fir into the GPU(s)? Also, what is the minimum channels StyleSwin (The generator part) can handle before it degrades in performance too much?

**Comment by ForeverFancy** [comment]
How well the model is performing. We do not perform experiments using less channels, you could try it.

**Comment by TheGullahanMaster** [comment]
Ok, I'm certainly trying it. 
BTW, does the accumulation depend on dataset size? `0.5 ** (32 / (10 * 1000))` is the equation, which i gather is making an EMA decay value (factor?)

**Comment by ForeverFancy** [comment]
> Ok, I'm certainly trying it. BTW, does the accumulation depend on dataset size? `0.5 ** (32 / (10 * 1000))` is the equation, which i gather is making an EMA decay value (factor?)

No.

**Comment by TheGullahanMaster** [comment]
How were the values chosen? Was tit though trial-and-error, or did it come from StyleGAN?

**Comment by ForeverFancy** [comment]
We adopt the setting from [StyleGAN implementation](https://github.com/rosinality/stylegan2-pytorch).

**Comment by TheGullahanMaster** [comment]
> 64x

You have mentioned in the previous "issue" (more like a discussion) that you've tried 64x64 at the beginning and it showed competitive performance. What hyperparameters did you use(channels, etc...)? Were they the same as they are now? Also, which dataset did you try with it?

**Comment by TheGullahanMaster** [comment]
Also also also, What hyperparameters should i focus on? Batch size, learning rates, bCR weights, R1?

**Comment by ForeverFancy** [comment]
> > > Thank you so much for the help, will try it as well. Say, the paper says you will start to see advantages of StyleSwin on 256x256 or higher. What are the results expected on smaller ones, like 128x128, or 64x64? Are they still very good? So far it seems pretty good, but the smallest i tried was 128x128. (MNIST i simply upscaled)
> > 
> > 
> > We have tried our model on 64x64 resolution in early exploration, the results are also competitive. Note that the best hyperparameters are different on each resolution, you may need to tune the hyper-param to obtain the best performance.
> 
> You have mentioned in the previous "issue" (more like a discussion) that you've tried 64x64 at the beginning and it showed competitive performance. What hyperparameters did you use(channels, etc...)? Were they the same as they are now? Also, which dataset did you try with it?

Same hyper-params as FFHQ-256. We tried on FFHQ-64.

**Comment by ForeverFancy** [comment]
> Also also also, What hyperparameters should i focus on? Batch size, learning rates, bCR weights, R1?

LR and r1.

**Comment by TheGullahanMaster** [comment]
> > > > Thank you so much for the help, will try it as well. Say, the paper says you will start to see advantages of StyleSwin on 256x256 or higher. What are the results expected on smaller ones, like 128x128, or 64x64? Are they still very good? So far it seems pretty good, but the smallest i tried was 128x128. (MNIST i simply upscaled)
> > > 
> > > 
> > > We have tried our model on 64x64 resolution in early exploration, the results are also competitive. Note that the best hyperparameters are different on each resolution, you may need to tune the hyper-param to obtain the best performance.
> > 
> > 
> > You have mentioned in the previous "issue" (more like a discussion) that you've tried 64x64 at the beginning and it showed competitive performance. What hyperparameters did you use(channels, etc...)? Were they the same as they are now? Also, which dataset did you try with it?
> 
> Same hyper-params as FFHQ-256. We tried on FFHQ-64.

Did you you keep the channels as they are in StyleGAN? (512 for 4x4, 512 for 8x8, 512 for 16x16, 512 for 32x32, 256 for 64x64)

**Comment by ForeverFancy** [comment]
yeah.

**Comment by TheGullahanMaster** [comment]
Thanks for reply :+1:
