### ISSUE TITLE
nvcc fatal: Unknown option '-generate-dependencies-with-compile'

### ISSUE THREAD

**Issue by navuboy** [microsoft/StyleSwin#27]
Hi, I was referring to your  github and trying to implement the StyleSwin repo. ecountering the following problem:
nvcc fatal   : Unknown option '-generate-dependencies-with-compile', not sure  whast the problem.
![Screenshot from 2022-07-11 13-45-56](https://user-images.githubusercontent.com/33291299/178257644-3310ea88-0947-48f3-b324-faf3fc8dbe42.png)

**Comment by ForeverFancy** [comment]
Hi, it seems that you are trying to pre-compile the CUDA ops? The CUDA ops in this repo don't need pre-compile and you could try to run the code directly. If the problem has not been solved in that way, you could provide more commands, envs and logs so that I could check it out to help. Thanks.

**Comment by nav74neet** [comment]
Thanks for the reply @ForeverFancy, I tried to run the training code (train_styleswin.py) directly and this is the terminal logs after execution:

`Traceback (most recent call last):
  File "/home/navneet/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1673, in _run_ninja_build
    env=env)
  File "/home/navneet/anaconda3/envs/py36/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_styleswin.py", line 27, in <module>
    from models.discriminator import Discriminator
  File "/home/navneet/Desktop/pp_research/StyleSwin/models/discriminator.py", line 7, in <module>
    from op import FusedLeakyReLU, upfirdn2d
  File "/home/navneet/Desktop/pp_research/StyleSwin/op/__init__.py", line 4, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/navneet/Desktop/pp_research/StyleSwin/op/fused_act.py", line 19, in <module>
    os.path.join(module_path, "fused_bias_act_kernel.cu"),
  File "/home/navneet/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1091, in load
    keep_intermediates=keep_intermediates)
  File "/home/navneet/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1302, in _jit_compile
    is_standalone=is_standalone)
  File "/home/navneet/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1407, in _write_ninja_file_and_build_library
    error_prefix=f"Error building extension '{name}'")
  File "/home/navneet/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused': [1/2] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output fused_bias_act_kernel.cuda.o.d -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/navneet/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include -isystem /home/navneet/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/navneet/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include/TH -isystem /home/navneet/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/navneet/anaconda3/envs/py36/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /home/navneet/Desktop/pp_research/StyleSwin/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
FAILED: fused_bias_act_kernel.cuda.o 
/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output fused_bias_act_kernel.cuda.o.d -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/navneet/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include -isystem /home/navneet/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/navneet/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include/TH -isystem /home/navneet/anaconda3/envs/py36/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/navneet/anaconda3/envs/py36/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++14 -c /home/navneet/Desktop/pp_research/StyleSwin/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
ninja: build stopped: subcommand failed.` 

I'm currently using an NVIDIA GeForce GPU. Will that be an issue.

**Comment by ForeverFancy** [comment]
What's the CUDA toolkit version you used?

**Comment by navuboy** [comment]
Its CUDA 11.6

**Comment by ForeverFancy** [comment]
Hi, maybe you could try the solution of [this link](https://discuss.pytorch.org/t/how-to-run-detectron2-using-rtx-3090-and-with-cuda-11-x-on-ubuntu/119448/9) to check whether that helps.
