### ISSUE TITLE
FID Curve

### ISSUE THREAD

**Issue by tau-yihouxiang** [microsoft/StyleSwin#29]
Great work! However, I use 4 x 3090 GPUs to train StyleSwin on the FFHQ-256 dataset, and evaluate FID on the same dataset. Then get the following FID curve from 0-500k after 4 days.

![image](https://user-images.githubusercontent.com/23013154/180390705-f0eeaa5c-0818-469a-95aa-fae686b7424f.png)

Is this normal? I might not see the probability of getting FID less than 10 after 1000k. Could you please show your FID curve in this dataset?

**Comment by tau-yihouxiang** [comment]
BTW, for each evaluation, the number of generated images is only 5000, because val_num_batches=1250 and val_batch_size=4.

**Comment by ForeverFancy** [comment]
We report FID between 50k generated images and 50k randomly selected images from FFHQ dataset, so maybe you should evaluate your training model again to see the fid score. The training fid curves could be found on [link1](https://wandb.ai/foreverfancy/FFHQ256_BCR_ChannelM2_DoubleAttn_Alpha/reports/fid-22-07-23-17-07-04---VmlldzoyMzYyMzU0?accessToken=y89drfnbxtdzmf17vkr8ew8s2unnis4jqwp30u615jsj466p2ez70g9su6f5818m) and [link2](https://wandb.ai/foreverfancy/FFHQ256_BCR_ChannelM2_DoubleAttn_Alpha_Lrdecay_Continue/reports/fid-22-07-23-17-07-06---VmlldzoyMzYyMzU2?accessToken=7z68x7auwtjk84epv8c4i9am7wivu1fjronb45f5sw5fzq78t07pab97td607th0).

**Comment by tau-yihouxiang** [comment]
Thank you! I got it.
