### ISSUE TITLE
Query: How to save the generated samples

### ISSUE THREAD

**Issue by KomputerMaster64** [microsoft/StyleSwin#31]
Thank you authors for sharing the interesting work you have done in deep generative modeling. I have a rather small doubt, this is regarding the command to generate samples.
```
python -m torch.distributed.launch --nproc_per_node=1 train_styleswin.py --sample_path /path_to_save_generated_samples --size 256 --G_channel_multiplier 2 --ckpt /path/to/checkpoint --eval --val_num_batches 12500 --val_batch_size 4 --eval_gt_path /path_to_real_images_50k
```
Here, I wanted to know what should be`path_to_save_generated_samples`?

I am getting the following error message:
```
Traceback (most recent call last):
  File "train_styleswin.py", line 382, in <module>
    os.mkdir(args.sample_path)
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Repositories/StyleSwin/StyleSwin_generated_samples/samples'
```
I made a directory in the cloned repository called `StyleSwin_generated_samples` for saving the samples.

**Comment by KomputerMaster64** [comment]
I changed the `/content/drive/MyDrive/Repositories/StyleSwin/StyleSwin_generated_samples/samples` to `/content/drive/MyDrive/Repositories/StyleSwin/imgs/` and the command is working.

Additionally, when I try the path `/content/drive/MyDrive/Repositories/StyleSwin/StyleSwin_generated_samples/samples/` (with `/` at the end of the path) it is still not working

**Comment by ForeverFancy** [comment]
Hi, please make sure your sample_path exist without `/samples` added. Thanks.

**Comment by KomputerMaster64** [comment]
Thank you for the response. 

I wanted to know how to modify `/path_to_real_images_50k`. What is the function of this argument? This is the final argument in the commands suggested [here](https://github.com/microsoft/StyleSwin#generating-image-samples-with-pretrained-model).

**Comment by ForeverFancy** [comment]
This augment is used to calculate fid score between the generated image samples and real image samples, which is used in [evaluation](https://github.com/microsoft/StyleSwin/blob/main/train_styleswin.py#L271). If you want to calculate fid score, please put the real images in /path_to_real_images_50k, otherwise, you should comment the fid score calculation in evaluation. Thanks.

**Comment by tongyi00** [comment]
> Thank you for the response.
> 
> I wanted to know how to modify `/path_to_real_images_50k`. What is the function of this argument? This is the final argument in the commands suggested [here](https://github.com/microsoft/StyleSwin#generating-image-samples-with-pretrained-model).

Hi,I encountered the same error as you, have you solved it?
