### ISSUE TITLE
Query: Samples in grid

### ISSUE THREAD

**Issue by KomputerMaster64** [microsoft/StyleSwin#32]
Thank you for the project. I wanted to know if one has saved the generated images in a directory, how to have them in a grid N*M dimensions for better analysis.

**Comment by ForeverFancy** [comment]
Hi, just modify the parameters in (torchvision.utils.save_image)[https://github.com/microsoft/StyleSwin/blob/main/train_styleswin.py#L286] to generate images in grid view. Thanks.
