### ISSUE TITLE
question strategy in resolution progression

### ISSUE THREAD

**Issue by JcccKing** [microsoft/StyleSwin#34]
Congratulations on this great job. I would like to ask you if your training strategy is similar to the StyleGAN resolution progression (e.g. 64x64, then 128x128) Thanks!

**Comment by ForeverFancy** [comment]
Hi, while StyleGANv1 uses progressive training, StyleGANv2 is directly trained to generate full-resolution images. We follow the training scheme of StyleGANv2 which does not have progressive training.

**Comment by JcccKing** [comment]
Thank you. I also paid attention to your billili and look forward to your new work.
