### ISSUE TITLE
cvpr2022 call for demos

### ISSUE THREAD

**Issue by AK391** [microsoft/StyleSwin#7]
Hi, there is a call for demos this year for cvpr 2022 

https://cvpr2022.thecvf.com/call-demos

where a demo can be added to the Hugging Face organization here: https://huggingface.co/cvpr

would you be interested in submitting a demo for this?

**Comment by ForeverFancy** [comment]
Sure! I have sent my request to join the CVPR org in huggingface, thanks for the reminder.
